import { createHash } from 'node:crypto'
import { z } from 'zod'
import { getHeader, isEvent, readBody, type H3Event } from 'h3'
import { sql, type Generated, type Kysely, type Migration, type Transaction } from 'kysely'
import type {
  ExtensionEntityTabContext,
  ExtensionScope,
  GcsExtensionCreateOperation,
  GcsExtensionJsonConfig,
  GcsLifecycleEntityAssignmentMode,
  GcsLifecycleEntityOwnerKind,
  GcsQualifiedExtensionEntityType,
  GcsFileStoragePurpose,
  GcsFileStorageTarget,
  JsonValue
} from './index'

export type { ExtensionEntityOwnerType, ExtensionEntityTabContext, ExtensionScope } from './index'
export type { GcsFileStoragePurpose, GcsFileStorageTarget } from './index'

export type GcsExtensionMigration = Migration

export type GcsFileStorageJsonObject = Record<string, JsonValue>

/** Maximum UTF-8 byte length of a stable provider-owned object identity. */
export const GCS_FILE_STORAGE_PROVIDER_OBJECT_ID_MAX_BYTES = 512

/** Agency- and provider-scoped secret reader supplied only to server adapters. */
export interface GcsFileStorageSecretReader {
  get: (key: string) => Promise<JsonValue | null>
}

export interface GcsFileStorageObjectReference {
  /** Stable provider-owned identity. It must not depend on a temporary access URL. */
  objectId: string
  /** Opaque, bounded JSON used only by the host server when calling this provider. */
  locator: GcsFileStorageJsonObject
}

export interface GcsFileStorageOperationContext extends GcsFileStorageObjectReference {
  agencyId: string
  purpose: GcsFileStoragePurpose
  target?: GcsFileStorageTarget
  agencyConfig: GcsExtensionJsonConfig
  secrets: GcsFileStorageSecretReader
}

export interface GcsFileStorageWriteObjectInput {
  /** Opaque collision-resistant name generated by the host. */
  objectName: string
  bytes: Uint8Array
  contentType: string
  agencyId: string
  purpose: GcsFileStoragePurpose
  target?: GcsFileStorageTarget
  agencyConfig: GcsExtensionJsonConfig
  secrets: GcsFileStorageSecretReader
  providerMetadata?: GcsFileStorageJsonObject
}

export interface GcsFileStorageReadObjectResult {
  bytes: Uint8Array
  contentType?: string
}

export interface GcsFileStorageProviderMetadataContext extends GcsFileStorageOperationContext {
  contractVersion: number
}

export interface GcsFileStorageUpdateProviderMetadataInput extends GcsFileStorageProviderMetadataContext {
  metadata: GcsFileStorageJsonObject
}

export interface GcsFileStorageProviderAdapterBase {
  /** Validates and normalizes agency configuration before the host persists it. */
  validateAgencyConfig?: (config: GcsExtensionJsonConfig) => Promise<GcsExtensionJsonConfig> | GcsExtensionJsonConfig
  writeObject: (input: GcsFileStorageWriteObjectInput) => Promise<GcsFileStorageObjectReference>
  readObject: (context: GcsFileStorageOperationContext) => Promise<GcsFileStorageReadObjectResult>
  /** Must succeed when the object is already absent. */
  deleteObject: (context: GcsFileStorageOperationContext) => Promise<void>
}

export interface GcsFileStorageProviderManagedMetadataAdapter extends GcsFileStorageProviderAdapterBase {
  readProviderMetadata: (
    context: GcsFileStorageProviderMetadataContext
  ) => Promise<GcsFileStorageJsonObject>
  updateProviderMetadata: (
    input: GcsFileStorageUpdateProviderMetadataInput
  ) => Promise<void>
}

export type GcsFileStorageProviderAdapter =
  | GcsFileStorageProviderAdapterBase
  | GcsFileStorageProviderManagedMetadataAdapter

export interface GcsFileStorageMetadataValidationContext {
  mode: 'create' | 'update'
  agencyId: string
  purpose: GcsFileStoragePurpose
  target?: GcsFileStorageTarget
  contractVersion: number
  agencyConfig: GcsExtensionJsonConfig
}

export type GcsFileStorageMetadataValidator = (
  metadata: GcsFileStorageJsonObject,
  context: GcsFileStorageMetadataValidationContext
) => Promise<GcsFileStorageJsonObject> | GcsFileStorageJsonObject

/** Preserves a typed storage adapter for generated host registration. */
export const defineGcsFileStorageProviderAdapter = <T extends GcsFileStorageProviderAdapter>(adapter: T): T => adapter

/** Preserves a typed provider metadata validator/normalizer for generated host registration. */
export const defineGcsFileStorageMetadataValidator = <T extends GcsFileStorageMetadataValidator>(validator: T): T => validator

/**
 * Preserves a typed Kysely migration for extension migration discovery.
 */
export const defineGcsExtensionMigration = <T extends GcsExtensionMigration>(migration: T): T => migration

const EXTENSION_KEY_PATTERN = /^[a-z][a-z0-9-]{0,62}$/
const LIFECYCLE_ENTITY_LOCAL_TYPE_PATTERN = /^[a-z][a-z0-9-]{0,62}$/
const SQL_IDENTIFIER_PATTERN = /^[a-z_][a-z0-9_]*$/

export interface GcsLifecycleEntityIdentityMigrationOptions {
  extensionKey: string
  localType: string
  table: string
  ownerKind: 'agreement' | 'proponent'
  ownerIdColumn: string
  schema?: string
  idColumn?: string
}

/** Produces the stable host identity for an extension-local entity type. */
export const qualifyGcsLifecycleEntityType = (
  extensionKey: string,
  localType: string
): GcsQualifiedExtensionEntityType => {
  if (!EXTENSION_KEY_PATTERN.test(extensionKey)) {
    throw new Error(`Invalid extension key "${extensionKey}"`)
  }
  if (!LIFECYCLE_ENTITY_LOCAL_TYPE_PATTERN.test(localType)) {
    throw new Error(`Invalid lifecycle entity local type "${localType}"`)
  }
  return `${extensionKey}:${localType}`
}

const assertSqlIdentifier = (value: string, fieldName: string): void => {
  if (!SQL_IDENTIFIER_PATTERN.test(value)) {
    throw new Error(`${fieldName} must be a lowercase PostgreSQL identifier`)
  }
}

const lifecycleIdentityObjectName = (
  prefix: 'fk' | 'trigger' | 'owner_bind' | 'owner_lock',
  qualifiedType: GcsQualifiedExtensionEntityType,
  table: string
): string => {
  const readable = `${qualifiedType}_${table}`.replaceAll(/[^a-z0-9_]/g, '_')
  const digest = createHash('sha256').update(`${qualifiedType}:${table}:${prefix}`).digest('hex').slice(0, 10)
  return `gcs_${prefix}_${readable.slice(0, 36)}_${digest}`
}

/**
 * Attaches an extension concrete table to the host polymorphic identity.
 *
 * The host must register the declaration in `Common_Entity_Type` before the
 * extension migration runs. The table must already contain a bigint-compatible
 * identity column whose value may be assigned by the BEFORE INSERT trigger.
 */
export const attachGcsLifecycleEntityIdentity = async (
  db: Kysely<unknown>,
  options: GcsLifecycleEntityIdentityMigrationOptions
): Promise<GcsQualifiedExtensionEntityType> => {
  const schema = options.schema ?? 'extensions'
  const idColumn = options.idColumn ?? 'id'
  assertSqlIdentifier(schema, 'schema')
  assertSqlIdentifier(options.table, 'table')
  assertSqlIdentifier(idColumn, 'idColumn')
  assertSqlIdentifier(options.ownerIdColumn, 'ownerIdColumn')
  if (options.ownerKind !== 'agreement' && options.ownerKind !== 'proponent') {
    throw new Error('ownerKind must be "agreement" or "proponent"')
  }

  const qualifiedType = qualifyGcsLifecycleEntityType(options.extensionKey, options.localType)
  const ownerType = options.ownerKind === 'agreement' ? 'fundingcaseagreement' : 'applicantrecipient'
  const registered = await sql<{ registered: boolean }>`
    SELECT EXISTS (
      SELECT 1
      FROM "Common_Entity_Type"
      WHERE egcs_cn_type = ${qualifiedType}
        AND egcs_cn_ownerkind = ${options.ownerKind}
        AND _deleted = false
    ) AS registered
  `.execute(db)
  if (registered.rows[0]?.registered !== true) {
    throw new Error(`Lifecycle entity type "${qualifiedType}" with owner kind "${options.ownerKind}" must be registered before extension migrations run`)
  }

  const relation = `${schema}.${options.table}`
  const foreignKeyName = lifecycleIdentityObjectName('fk', qualifiedType, options.table)
  const triggerName = lifecycleIdentityObjectName('trigger', qualifiedType, options.table)
  const ownerBindingTriggerName = lifecycleIdentityObjectName('owner_bind', qualifiedType, options.table)
  const ownerLockTriggerName = lifecycleIdentityObjectName('owner_lock', qualifiedType, options.table)
  const existingForeignKey = await sql<{ present: boolean }>`
    SELECT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = ${foreignKeyName}
        AND conrelid = ${relation}::regclass
    ) AS present
  `.execute(db)

  if (existingForeignKey.rows[0]?.present !== true) {
    await sql`
      ALTER TABLE ${sql.id(schema, options.table)}
      ADD CONSTRAINT ${sql.id(foreignKeyName)}
      FOREIGN KEY (${sql.id(idColumn)})
      REFERENCES "Common_Entity"(id)
      ON DELETE RESTRICT
    `.execute(db)
  }

  await sql`
    DROP TRIGGER IF EXISTS ${sql.id(triggerName)}
    ON ${sql.id(schema, options.table)}
  `.execute(db)
  await sql`
    CREATE TRIGGER ${sql.id(triggerName)}
    BEFORE INSERT ON ${sql.id(schema, options.table)}
    FOR EACH ROW EXECUTE FUNCTION register_entity(${sql.lit(qualifiedType)})
  `.execute(db)
  await sql`
    DROP TRIGGER IF EXISTS ${sql.id(ownerBindingTriggerName)}
    ON ${sql.id(schema, options.table)}
  `.execute(db)
  await sql`
    CREATE TRIGGER ${sql.id(ownerBindingTriggerName)}
    AFTER INSERT ON ${sql.id(schema, options.table)}
    FOR EACH ROW EXECUTE FUNCTION bind_extension_entity_owner(
      ${sql.lit(qualifiedType)},
      ${sql.lit(idColumn)},
      ${sql.lit(ownerType)},
      ${sql.lit(options.ownerIdColumn)}
    )
  `.execute(db)
  await sql`
    DROP TRIGGER IF EXISTS ${sql.id(ownerLockTriggerName)}
    ON ${sql.id(schema, options.table)}
  `.execute(db)
  await sql`
    CREATE TRIGGER ${sql.id(ownerLockTriggerName)}
    BEFORE UPDATE OF ${sql.id(options.ownerIdColumn)} ON ${sql.id(schema, options.table)}
    FOR EACH ROW EXECUTE FUNCTION lock_extension_entity_owner_column(${sql.lit(options.ownerIdColumn)})
  `.execute(db)

  return qualifiedType
}

export interface GcsLifecycleEntityTarget {
  entityType: GcsQualifiedExtensionEntityType
  entityId: string
}

export interface GcsLifecycleEntityAdapterContext {
  event: unknown
  transaction: Transaction<unknown>
  actorUserId: string
}

export interface GcsLifecycleEntityOwnerResolution {
  owner: GcsLifecycleEntityOwnerKind
  ownerId: string
  agencyId: string
  streamId?: string
}

export interface GcsLifecycleEntityScopeResolution {
  agencyId: string
  streamId?: string
  scope: ExtensionScope
}

export interface GcsLifecycleEntityStatusResolution {
  statusId: string
  readOnly: boolean
  terminal: boolean
  isDraft: boolean
}

export interface GcsLockedLifecycleEntity {
  target: GcsLifecycleEntityTarget
  owner: GcsLifecycleEntityOwnerResolution
  scope: GcsLifecycleEntityScopeResolution
  status: GcsLifecycleEntityStatusResolution
  assignmentMode: GcsLifecycleEntityAssignmentMode
  /** Adapter-owned locked snapshot used only inside the current transaction. */
  record: unknown
}

export interface GcsLifecycleEntityCompletionValidationContext {
  completionId: string
  lockedEntity: GcsLockedLifecycleEntity
}

export interface GcsLifecycleEntityStatusMutationContext {
  lockedEntity: GcsLockedLifecycleEntity
  nextStatusId: string
  runtimeId: string
}

export interface GcsLifecycleEntityPositiveTerminusContext {
  completionId: string
  lockedEntity: GcsLockedLifecycleEntity
  runtimeId?: string
}

/**
 * Host-invoked adapter for an extension lifecycle entity. The host retains
 * authorization, transaction boundaries, lock ordering, Completion evidence,
 * Workflow execution, and status-transition history.
 */
export interface GcsExtensionLifecycleEntityAdapter {
  registerIdentity: (
    context: GcsLifecycleEntityAdapterContext,
    target: GcsLifecycleEntityTarget
  ) => Promise<void> | void
  resolveOwner: (
    context: GcsLifecycleEntityAdapterContext,
    target: GcsLifecycleEntityTarget
  ) => Promise<GcsLifecycleEntityOwnerResolution | null> | GcsLifecycleEntityOwnerResolution | null
  resolveScope: (
    context: GcsLifecycleEntityAdapterContext,
    target: GcsLifecycleEntityTarget
  ) => Promise<GcsLifecycleEntityScopeResolution | null> | GcsLifecycleEntityScopeResolution | null
  resolveStatus: (
    context: GcsLifecycleEntityAdapterContext,
    target: GcsLifecycleEntityTarget
  ) => Promise<GcsLifecycleEntityStatusResolution | null> | GcsLifecycleEntityStatusResolution | null
  lockEntity: (
    context: GcsLifecycleEntityAdapterContext,
    target: GcsLifecycleEntityTarget
  ) => Promise<GcsLockedLifecycleEntity | null>
  validateCompletion: (
    context: GcsLifecycleEntityAdapterContext,
    completion: GcsLifecycleEntityCompletionValidationContext
  ) => Promise<void> | void
  mutateStatus: (
    context: GcsLifecycleEntityAdapterContext,
    mutation: GcsLifecycleEntityStatusMutationContext
  ) => Promise<void>
  onPositiveTerminus?: (
    context: GcsLifecycleEntityAdapterContext,
    terminus: GcsLifecycleEntityPositiveTerminusContext
  ) => Promise<void> | void
}

/** Preserves a typed lifecycle adapter for generated host registration. */
export const defineGcsLifecycleEntityAdapter = <T extends GcsExtensionLifecycleEntityAdapter>(adapter: T): T => adapter

export const GCS_EXTENSION_CREATE_OPERATION_HOOK = 'gcs:extension:create-operation'
export const GCS_EXTENSION_DISABLE_GUARD_HOOK = 'gcs:extension:disable-guard'
export const GCS_EXTENSION_AGREEMENT_LIFECYCLE_LOCK_HOOK
  = 'gcs:extension:agreement-lifecycle-lock'
export const GCS_EXTENSION_AGREEMENT_STREAM_CHANGE_GUARD_HOOK
  = 'gcs:extension:agreement-stream-change-guard'
export const GCS_EXTENSION_AGREEMENT_PAYMENT_MUTATION_GUARD_HOOK
  = 'gcs:extension:agreement-payment-mutation-guard'
export const GCS_EXTENSION_AGREEMENT_DELETE_GUARD_HOOK
  = 'gcs:extension:agreement-delete-guard'
export const GCS_EXTENSION_STATUS_REFERENCE_GUARD_HOOK
  = 'gcs:extension:status-reference-guard'
export const GCS_EXTENSION_CONFIGURATION_GUARD_HOOK
  = 'gcs:extension:configuration-guard'

export type GcsExtensionDisableScope = 'agency' | 'stream'

export interface GcsExtensionDisableGuardContext {
  extensionKey: string
  scope: GcsExtensionDisableScope
  event: unknown
  db: Transaction<unknown>
  agencyId: string
  streamId?: string
}

export type GcsExtensionDisableGuardHandler = (
  context: GcsExtensionDisableGuardContext
) => Promise<void> | void

const getExtensionLifecycleLockKey = (
  extensionKey: string,
  scope: GcsExtensionDisableScope,
  scopeId: string
): string => `gcs-extension-lifecycle:${extensionKey}:${scope}:${scopeId}`

/**
 * Serializes extension lifecycle work with host agency and stream configuration mutations.
 *
 * Agency scope is always acquired before stream scope. Extension handlers must take these
 * locks before entity-level locks so configuration changes cannot race generated work.
 */
export const lockGcsExtensionLifecycleScope = async (
  db: Transaction<unknown>,
  extensionKey: string,
  agencyId: string,
  streamId?: string
): Promise<void> => {
  await sql`
    select pg_advisory_xact_lock(
      hashtextextended(${getExtensionLifecycleLockKey(extensionKey, 'agency', agencyId)}, 0)
    )
  `.execute(db)

  if (streamId !== undefined) {
    await sql`
      select pg_advisory_xact_lock(
        hashtextextended(${getExtensionLifecycleLockKey(extensionKey, 'stream', streamId)}, 0)
      )
    `.execute(db)
  }
}

export interface GcsExtensionDisableGuardHookPayload extends GcsExtensionDisableGuardContext {}

export interface GcsExtensionAgreementLifecycleLockContext {
  extensionKey: string
  event: unknown
  db: Transaction<unknown>
  agreementId: string
  agencyId: string
  currentStreamId: string
  targetStreamIds: string[]
}

export type GcsExtensionAgreementLifecycleLockHandler = (
  context: GcsExtensionAgreementLifecycleLockContext
) => Promise<void> | void

export type GcsExtensionAgreementLifecycleLockHookPayload = Omit<
  GcsExtensionAgreementLifecycleLockContext,
  'extensionKey'
>

export interface GcsExtensionAgreementStreamChangeGuardContext {
  extensionKey: string
  event: unknown
  db: Transaction<unknown>
  agreementId: string
  agencyId: string
  currentStreamId: string
  nextStreamId: string
}

export type GcsExtensionAgreementStreamChangeGuardHandler = (
  context: GcsExtensionAgreementStreamChangeGuardContext
) => Promise<void> | void

export type GcsExtensionAgreementStreamChangeGuardHookPayload = Omit<
  GcsExtensionAgreementStreamChangeGuardContext,
  'extensionKey'
>

export type GcsExtensionAgreementPaymentMutation =
  | 'payment.update'
  | 'payment.delete'
  | 'payment.status-change'
  | 'payment-line.create'
  | 'payment-line.update'
  | 'payment-line.delete'

export interface GcsExtensionAgreementPaymentMutationGuardContext {
  extensionKey: string
  operation: GcsExtensionAgreementPaymentMutation
  event: unknown
  db: Transaction<unknown>
  agreementId: string
  paymentId: string
  paymentLineId?: string
  currentStatusId?: string
  nextStatusId?: string
  changes?: Record<string, unknown>
}

export type GcsExtensionAgreementPaymentMutationGuardHandler = (
  context: GcsExtensionAgreementPaymentMutationGuardContext
) => Promise<void> | void

export type GcsExtensionAgreementPaymentMutationGuardHookPayload = Omit<
  GcsExtensionAgreementPaymentMutationGuardContext,
  'extensionKey'
>

export interface GcsExtensionAgreementDeleteGuardContext {
  extensionKey: string
  event: unknown
  db: Transaction<unknown>
  agreementId: string
  agencyId: string
  streamId: string
}

export type GcsExtensionAgreementDeleteGuardHandler = (
  context: GcsExtensionAgreementDeleteGuardContext
) => Promise<void> | void

export type GcsExtensionAgreementDeleteGuardHookPayload = Omit<
  GcsExtensionAgreementDeleteGuardContext,
  'extensionKey'
>

export interface GcsExtensionStatusReferenceGuardContext {
  extensionKey: string
  event: unknown
  db: Transaction<unknown>
  agencyId: string
  statusId: string
}

export type GcsExtensionStatusReferenceGuardHandler = (
  context: GcsExtensionStatusReferenceGuardContext
) => Promise<void> | void

export type GcsExtensionStatusReferenceGuardHookPayload = Omit<
  GcsExtensionStatusReferenceGuardContext,
  'extensionKey'
>

export interface GcsExtensionConfigurationGuardContext {
  extensionKey: string
  targetExtensionKey: string
  event: unknown
  db: Transaction<unknown>
  scope: GcsExtensionDisableScope
  agencyId: string
  streamId?: string
  enabled: boolean
  config?: GcsExtensionJsonConfig
}

export type GcsExtensionConfigurationGuardHandler = (
  context: GcsExtensionConfigurationGuardContext
) => Promise<void> | void

export type GcsExtensionConfigurationGuardHookPayload = Omit<
  GcsExtensionConfigurationGuardContext,
  'extensionKey'
>

export interface ExtensionStreamContext {
  agencyId: string
  profileId: string
  streamId: string
  scope: ExtensionScope
}

export interface GcsExtensionCreateOperationContext {
  operation: GcsExtensionCreateOperation
  phase: 'before-create' | 'after-create'
  extensionKey: string
  event: unknown
  db: Kysely<unknown>
  trx: Kysely<unknown>
  agreementId: string
  agencyId: string
  streamId: string
  scope: ExtensionScope
  config: GcsExtensionJsonConfig
  validatedBody: Record<string, unknown>
  createdRecord?: Record<string, unknown>
}

export type GcsExtensionCreateOperationResult =
  | {
    status: 'handled'
    response: unknown
  }
  | {
    status: 'continue'
  }

export type GcsExtensionCreateOperationHandler = (
  context: GcsExtensionCreateOperationContext
) => Promise<GcsExtensionCreateOperationResult | void> | GcsExtensionCreateOperationResult | void

export interface GcsExtensionCreateOperationHookPayload {
  operation: GcsExtensionCreateOperation
  enabledExtensionKeys: Set<string>
  contexts: Record<string, Omit<GcsExtensionCreateOperationContext, 'extensionKey' | 'config'> & {
    config: GcsExtensionJsonConfig
  }>
  results: Array<{
    extensionKey: string
    result: GcsExtensionCreateOperationResult
  }>
}

type NitroHookRegistrar = {
  hooks: {
    hook: {
      (
        name: typeof GCS_EXTENSION_CREATE_OPERATION_HOOK,
        handler: (payload: GcsExtensionCreateOperationHookPayload) => Promise<void> | void
      ): void
      (
        name: typeof GCS_EXTENSION_DISABLE_GUARD_HOOK,
        handler: (payload: GcsExtensionDisableGuardHookPayload) => Promise<void> | void
      ): void
      (
        name: typeof GCS_EXTENSION_AGREEMENT_LIFECYCLE_LOCK_HOOK,
        handler: (payload: GcsExtensionAgreementLifecycleLockHookPayload) => Promise<void> | void
      ): void
      (
        name: typeof GCS_EXTENSION_AGREEMENT_STREAM_CHANGE_GUARD_HOOK,
        handler: (payload: GcsExtensionAgreementStreamChangeGuardHookPayload) => Promise<void> | void
      ): void
      (
        name: typeof GCS_EXTENSION_AGREEMENT_PAYMENT_MUTATION_GUARD_HOOK,
        handler: (payload: GcsExtensionAgreementPaymentMutationGuardHookPayload) => Promise<void> | void
      ): void
      (
        name: typeof GCS_EXTENSION_AGREEMENT_DELETE_GUARD_HOOK,
        handler: (payload: GcsExtensionAgreementDeleteGuardHookPayload) => Promise<void> | void
      ): void
      (
        name: typeof GCS_EXTENSION_STATUS_REFERENCE_GUARD_HOOK,
        handler: (payload: GcsExtensionStatusReferenceGuardHookPayload) => Promise<void> | void
      ): void
      (
        name: typeof GCS_EXTENSION_CONFIGURATION_GUARD_HOOK,
        handler: (payload: GcsExtensionConfigurationGuardHookPayload) => Promise<void> | void
      ): void
      (
      name: string,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Nitro permits arbitrary hook payload shapes
        handler: (payload: any) => Promise<void> | void
      ): void
    }
  }
}

export interface GcsExtensionRouteEvent {
  node?: {
    res?: {
      statusCode?: number
      statusMessage?: string
    }
  }
  context: {
    $authContext?: GcsExtensionAuthContext
    $db: unknown
    gcsExtension?: {
      extensionKey?: string
      config: GcsExtensionJsonConfig | unknown
      writeAuthorization?: GcsExtensionWriteAuthorization
      agreementAccess?: GcsExtensionAgreementAccess
      entity?: Record<string, unknown>
      stream?: Record<string, unknown>
      agency?: Record<string, unknown>
    }
    params?: Record<string, string | undefined>
  }
}

export interface GcsExtensionRouteContext {
  event: GcsExtensionRouteEvent
  db: unknown
  params: Record<string, string | undefined>
  auth?: GcsExtensionAuthContext
  extensionKey?: string
  config: GcsExtensionJsonConfig | unknown
  entity?: Record<string, unknown>
  stream?: Record<string, unknown>
  agency?: Record<string, unknown>
  authorizedScope?: ExtensionScope
  writeAuthorization?: GcsExtensionWriteAuthorization
  agreementAccess?: GcsExtensionAgreementAccess
  readBody: <T = unknown>() => Promise<T>
  getHeader: (name: string) => string | undefined
}

export interface GcsExtensionAuthContext {
  userId: string
  userAbilities: {
    authorize: (subject: string, action: string, scope: ExtensionScope) => boolean
  }
}

/**
 * Money accepted at an extension-to-host write boundary.
 *
 * Canonical decimal text is authoritative and is required for values outside the
 * exact JavaScript-number compatibility range. It uses plain decimal notation
 * with no exponent and at most two fractional digits; the host canonicalizes it
 * to two fractional digits and enforces its persisted money range.
 *
 * Finite numbers remain accepted for backwards compatibility only. They must
 * round-trip to exact cents within `Number.MAX_SAFE_INTEGER`; new extension code
 * should send canonical decimal text instead.
 */
export type GcsExtensionMoneyInput = string | number

export interface GcsExtensionAgreementClaimLineItemCreateInput {
  budgetLineItemId: string | null
  submittedCostCategory: string | null
  submittedCostSubsection: string | null
  submittedLineItem: string | null
  description: string
  /** Exact Claim line amount. Canonical decimal text is authoritative; numbers are deprecated compatibility input. */
  amount: GcsExtensionMoneyInput
  currency: string
}

export interface GcsExtensionAgreementClaimCreateInput {
  agreementId: string
  streamId: string
  fiscalYearId: string
  isFinalForYear: boolean
  periodStart: number
  periodEnd: number
  receivedDate: Date
  submissionUuid: string | null
  expectedDraftStatusId?: string
  lineItems: GcsExtensionAgreementClaimLineItemCreateInput[]
}

export type GcsExtensionAgreementClaimCreateResult =
  | {
      status: 'created'
      claimId: string
      lineItemIds: string[]
      draftStatusId: string
    }
  | {
      status:
        | 'agreement_unavailable'
        | 'fiscal_year_unavailable'
        | 'requested_status_unavailable'
        | 'requested_status_not_draft'
    }

/** Host-owned authorization phases for extension transactions that acquire lifecycle locks. */
export interface GcsExtensionWriteAuthorization {
  /** Locks and rebuilds the current user's grant graph before extension lifecycle locks. */
  lockAuthState: (db: unknown) => Promise<void>
  /** Re-resolves and authorizes the current agency, stream, or entity after extension lifecycle locks. */
  authorizeCurrentScope?: (db: unknown) => Promise<void>
  /** Compatibility alias for extensions built against the original entity-only write protocol. */
  authorizeCurrentEntity: (db: unknown) => Promise<void>
  /** Locks, re-resolves, and freshly authorizes an agreement in the owning transaction. */
  lockAndAuthorizeAgreement?: (
    db: unknown,
    input: { agreementId: string; streamId: string; action: 'update' | 'delete' }
  ) => Promise<boolean>
  /** Freshly authorizes and atomically creates a Draft Claim aggregate and creator-primary assignment. */
  createAgreementClaim?: (
    db: unknown,
    input: GcsExtensionAgreementClaimCreateInput
  ) => Promise<GcsExtensionAgreementClaimCreateResult>
}

export interface GcsExtensionAgreementOption {
  id: string
  agreementNumber: string
  label: string
}

/** Host-owned agreement visibility queries for extension routes. */
export interface GcsExtensionAgreementAccess {
  listVisibleOptions: (
    db: unknown,
    input: { streamId: string; action: 'read' | 'update' }
  ) => Promise<GcsExtensionAgreementOption[]>
}

export type GcsExtensionRawRouteHandler<T = unknown> = (
  event: GcsExtensionRouteEvent
) => T | Promise<T>

export type GcsExtensionRouteHandler<T = unknown> = (
  context: GcsExtensionRouteContext
) => T | Promise<T>

/**
 * Adapts a host route event and injected extension metadata to the public extension route context.
 */
export const createGcsExtensionRouteContext = (event: GcsExtensionRouteEvent): GcsExtensionRouteContext => {
  const context: GcsExtensionRouteContext = {
    event,
    db: event.context.$db,
    params: event.context.params ?? {},
    config: event.context.gcsExtension?.config ?? {},
    readBody: async <T = unknown>() => await readGcsExtensionRequestBody<T>(event),
    getHeader: (name: string) => getGcsExtensionRequestHeader(event, name)
  }
  if (event.context.$authContext) {
    context.auth = event.context.$authContext
  }
  if (event.context.gcsExtension?.extensionKey) {
    context.extensionKey = event.context.gcsExtension.extensionKey
  }
  if (event.context.gcsExtension?.writeAuthorization) {
    context.writeAuthorization = event.context.gcsExtension.writeAuthorization
  }
  if (event.context.gcsExtension?.agreementAccess) {
    context.agreementAccess = event.context.gcsExtension.agreementAccess
  }
  if (event.context.gcsExtension?.entity) {
    context.entity = event.context.gcsExtension.entity
    if (isExtensionScope(event.context.gcsExtension.entity.scope)) {
      context.authorizedScope = event.context.gcsExtension.entity.scope
    }
  }
  if (event.context.gcsExtension?.stream) {
    context.stream = event.context.gcsExtension.stream
    if (isExtensionScope(event.context.gcsExtension.stream.scope)) {
      context.authorizedScope = event.context.gcsExtension.stream.scope
    }
  }
  if (event.context.gcsExtension?.agency) {
    context.agency = event.context.gcsExtension.agency
    if (isExtensionScope(event.context.gcsExtension.agency.scope)) {
      context.authorizedScope = event.context.gcsExtension.agency.scope
    }
  }

  return context
}

const isExtensionScope = (value: unknown): value is ExtensionScope =>
  value !== null
  && typeof value === 'object'
  && 'type' in value

/**
 * Wraps a context-based extension handler as a host event handler.
 */
export const defineGcsExtensionRouteHandler = <T>(
  handler: GcsExtensionRouteHandler<T>
): GcsExtensionRawRouteHandler<T> =>
  async (event: GcsExtensionRouteEvent) => await handler(createGcsExtensionRouteContext(event))

const requireHostH3Event = (
  eventOrContext: GcsExtensionRouteEvent | GcsExtensionRouteContext
): H3Event => {
  const event = 'event' in eventOrContext ? eventOrContext.event : eventOrContext
  if (!isEvent(event)) {
    throw new TypeError('GCS extension request helpers require a host H3 event.')
  }

  return event
}

/**
 * Reads the request body from either a host event or an extension route context.
 */
export const readGcsExtensionRequestBody = async <T = unknown>(
  eventOrContext: GcsExtensionRouteEvent | GcsExtensionRouteContext
): Promise<T> => await readBody<T>(requireHostH3Event(eventOrContext))

/**
 * Reads a request header from either a host event or an extension route context.
 */
export const getGcsExtensionRequestHeader = (
  eventOrContext: GcsExtensionRouteEvent | GcsExtensionRouteContext,
  name: string
): string | undefined => getHeader(requireHostH3Event(eventOrContext), name)

/**
 * Resolves a hook database supplied directly or through its host event context.
 */
export const getGcsExtensionHookDatabase = (payload: {
  db?: unknown
  event?: {
    context?: {
      $db?: unknown
    }
  }
}): unknown => payload.db ?? payload.event?.context?.$db

/**
 * Registers through the host Nitro global when present, otherwise preserving the plugin for tests and tooling.
 */
export const defineGcsExtensionNitroPlugin = <T extends (nitroApp: NitroHookRegistrar) => Promise<void> | void>(
  plugin: T
): T => {
  const globalDefine = (globalThis as typeof globalThis & {
    defineNitroPlugin?: (plugin: T) => T
  }).defineNitroPlugin

  return globalDefine ? globalDefine(plugin) : plugin
}

export type GcsExtensionLocalizedMessage =
  | string
  | {
    en: string
    fr: string
  }

export interface GcsExtensionUserErrorDetail {
  /**
   * Stable field or domain path for the problem, such as `egcs_fc_paymentamount`
   * or `allocation.lines.0.amount`. The host serializes this path so clients can
   * show field-specific messages when they choose to.
   */
  path: string
  /**
   * Extension-owned user-facing message. Prefer `{ en, fr }` so the host can
   * select the request locale. Plain strings are treated as already-resolved
   * extension text and are not translated by the host.
   */
  message: GcsExtensionLocalizedMessage
  /**
   * Optional stable extension-owned detail code for logs, tests, and client-side
   * fallback handling.
   */
  code?: string
}

export interface GcsExtensionUserErrorOptions {
  /**
   * Stable extension-owned error code. Prefix with the extension key or another
   * unique namespace, for example `GCS_EXAMPLE_PAYMENT_RULES_MISSING`.
   */
  code: string
  /**
   * Helpful, user-correctable, extension-owned message. Prefer bilingual
   * messages. Do not pass host i18n keys here.
   */
  message: GcsExtensionLocalizedMessage
  /**
   * Defaults to 400. Use 409 for conflicts or another 4xx when it better
   * describes a user-correctable extension rule failure.
   */
  statusCode?: number
  /**
   * Field/domain-specific detail messages. The host resolves bilingual details
   * and returns them as `data.details[]` in the API error payload.
   */
  details?: GcsExtensionUserErrorDetail[]
}

const defaultLocalizedMessage = (message: GcsExtensionLocalizedMessage): string =>
  typeof message === 'string' ? message : message.en

/**
 * Carries a stable code, HTTP status, localized message, and optional details across the host error boundary.
 */
export class GcsExtensionUserError extends Error {
  readonly code: string
  readonly statusCode: number
  readonly localizedMessage: GcsExtensionLocalizedMessage
  readonly details?: GcsExtensionUserErrorOptions['details']

  constructor(options: GcsExtensionUserErrorOptions) {
    super(defaultLocalizedMessage(options.message))
    this.name = 'GcsExtensionUserError'
    this.code = options.code
    this.statusCode = options.statusCode ?? 400
    this.localizedMessage = options.message
    this.details = options.details
  }
}

/**
 * Creates a structured extension-owned user error from localized options.
 */
export const createGcsExtensionUserError = (options: GcsExtensionUserErrorOptions): GcsExtensionUserError =>
  new GcsExtensionUserError(options)

/**
 * Recognizes local instances and structurally compatible extension user errors from another module realm.
 */
export const isGcsExtensionUserError = (error: unknown): error is GcsExtensionUserError =>
  error instanceof GcsExtensionUserError
  || (
    Boolean(error)
    && typeof error === 'object'
    && (error as { name?: unknown }).name === 'GcsExtensionUserError'
    && typeof (error as { code?: unknown }).code === 'string'
    && typeof (error as { message?: unknown }).message === 'string'
  )

/**
 * Registers an enabled-operation hook that appends a handler result for the extension's injected context.
 */
export const registerGcsExtensionCreateOperationHandler = (
  extensionKey: string,
  operation: GcsExtensionCreateOperation,
  handler: GcsExtensionCreateOperationHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension create operation handlers must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_CREATE_OPERATION_HOOK, async payload => {
    if (payload.operation !== operation || !payload.enabledExtensionKeys.has(extensionKey)) {
      return
    }

    const context = payload.contexts[extensionKey]
    if (!context) {
      return
    }

    const result = await handler({
      ...context,
      extensionKey
    })

    if (result) {
      payload.results.push({
        extensionKey,
        result
      })
    }
  })
}

/**
 * Registers an extension-owned guard that runs through the host's actual disable lifecycle.
 */
export const registerGcsExtensionDisableGuard = (
  extensionKey: string,
  handler: GcsExtensionDisableGuardHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension disable guards must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_DISABLE_GUARD_HOOK, async payload => {
    if (payload.extensionKey !== extensionKey) {
      return
    }

    await handler(payload)
  })
}

/**
 * Registers extension agreement locks that must run after scope locks and before the host profile row lock.
 */
export const registerGcsExtensionAgreementLifecycleLock = (
  extensionKey: string,
  handler: GcsExtensionAgreementLifecycleLockHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension agreement lifecycle locks must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_AGREEMENT_LIFECYCLE_LOCK_HOOK, async payload => {
    await handler({
      ...payload,
      extensionKey
    })
  })
}

/**
 * Registers an extension-owned guard that runs before the host reassigns an agreement stream.
 */
export const registerGcsExtensionAgreementStreamChangeGuard = (
  extensionKey: string,
  handler: GcsExtensionAgreementStreamChangeGuardHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension agreement stream change guards must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_AGREEMENT_STREAM_CHANGE_GUARD_HOOK, async payload => {
    await handler({
      ...payload,
      extensionKey
    })
  })
}

/**
 * Registers an extension-owned guard that runs inside host payment mutation transactions.
 */
export const registerGcsExtensionAgreementPaymentMutationGuard = (
  extensionKey: string,
  handler: GcsExtensionAgreementPaymentMutationGuardHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension agreement payment mutation guards must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_AGREEMENT_PAYMENT_MUTATION_GUARD_HOOK, async payload => {
    await handler({
      ...payload,
      extensionKey
    })
  })
}

/**
 * Registers an extension-owned guard that runs inside the locked host agreement deletion transaction.
 */
export const registerGcsExtensionAgreementDeleteGuard = (
  extensionKey: string,
  handler: GcsExtensionAgreementDeleteGuardHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension agreement delete guards must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_AGREEMENT_DELETE_GUARD_HOOK, async payload => {
    await handler({
      ...payload,
      extensionKey
    })
  })
}

/**
 * Registers an extension-owned guard for Agency status deletion reference checks.
 */
export const registerGcsExtensionStatusReferenceGuard = (
  extensionKey: string,
  handler: GcsExtensionStatusReferenceGuardHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension status reference guards must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_STATUS_REFERENCE_GUARD_HOOK, async payload => {
    await handler({
      ...payload,
      extensionKey
    })
  })
}

/**
 * Registers an extension-owned validator for host-managed Agency or stream configuration writes.
 */
export const registerGcsExtensionConfigurationGuard = (
  extensionKey: string,
  handler: GcsExtensionConfigurationGuardHandler,
  nitroApp?: NitroHookRegistrar
) => {
  const resolvedNitroApp = nitroApp ?? (globalThis as typeof globalThis & {
    useNitroApp?: () => NitroHookRegistrar
  }).useNitroApp?.()

  if (!resolvedNitroApp) {
    throw new Error('GCS extension configuration guards must be registered from a Nitro plugin.')
  }

  resolvedNitroApp.hooks.hook(GCS_EXTENSION_CONFIGURATION_GUARD_HOOK, async payload => {
    await handler({
      ...payload,
      extensionKey
    })
  })
}

export interface ExtensionAgreementLookupDatabase {
  Funding_Case_Agreement_Profile: {
    id: unknown
    egcs_fc_fundingagreement: string | null
    egcs_fc_transferpaymentstream: unknown
    _deleted: boolean
  }
}

export interface ExtensionAgreementLookupResult {
  id: string
  agreementNumber: string
  streamId: string
}

/**
 * Resolves one non-deleted agreement by number and optional stream, returning normalized string identifiers.
 */
export const resolveExtensionAgreementByNumber = async (
  db: Kysely<ExtensionAgreementLookupDatabase>,
  agreementNumber: string,
  streamId?: string
): Promise<ExtensionAgreementLookupResult | null> => {
  let query = db
    .selectFrom('Funding_Case_Agreement_Profile')
    .select([
      'id',
      'egcs_fc_fundingagreement',
      'egcs_fc_transferpaymentstream'
    ])
    .where('egcs_fc_fundingagreement', '=', agreementNumber)
    .where('_deleted', '=', false)

  if (streamId !== undefined) {
    query = query.where('egcs_fc_transferpaymentstream', '=', streamId)
  }

  const agreement = await query.executeTakeFirst()
  if (!agreement || !agreement.egcs_fc_fundingagreement) {
    return null
  }

  return {
    id: String(agreement.id),
    agreementNumber: agreement.egcs_fc_fundingagreement,
    streamId: String(agreement.egcs_fc_transferpaymentstream)
  }
}

export interface ExtensionExternalSubmissionIdentity {
  extensionKey: string
  ownerType: string
  ownerId: string
  submissionUuid: string
}

type ExtensionKvDatabase = {
  'extensions.kv_entry': {
    id: unknown
    extension_key: string
    owner_type: string
    owner_id: string
    config_key: string
    value: JsonValue
    _deleted: boolean
  }
}

/** Database columns used by the host-managed encrypted extension secret store. */
export interface ExtensionSecretEntryTable {
  id: Generated<string>
  extension_key: string
  owner_type: string
  owner_id: string
  secret_key: string
  ciphertext: string
  iv: string
  auth_tag: string
  algorithm: string
  key_version: number
  metadata: Generated<JsonValue>
  created_at: Generated<Date | string>
  updated_at: Date | string | null
  _deleted: Generated<boolean>
}

/** Minimal database contract required by encrypted extension secret helpers. */
export interface ExtensionSecretDatabase {
  'extensions.secret_entry': ExtensionSecretEntryTable
}

type ExtensionSecretDatabaseClient<Database extends ExtensionSecretDatabase> =
  Kysely<Database> | Transaction<Database>

/** Narrows Kysely's invariant database generic after the public constraint proves the secret table shape. */
const asExtensionSecretDatabase = <Database extends ExtensionSecretDatabase>(
  db: ExtensionSecretDatabaseClient<Database>
): Kysely<ExtensionSecretDatabase> => db as unknown as Kysely<ExtensionSecretDatabase>

interface ExtensionSecretOptions {
  rootKey: string
  extensionKey: string
  ownerType: string
  ownerId: string
  secretKey: string
}

interface SetExtensionSecretOptions extends ExtensionSecretOptions {
  value: JsonValue
  metadata?: JsonValue
}

const EXTENSION_SECRET_ALGORITHM = 'AES-256-GCM'
const EXTENSION_SECRET_KEY_VERSION = 1
const EXTENSION_SECRET_IV_BYTES = 12
const EXTENSION_SECRET_TAG_BYTES = 16

const base64Alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

const bytesToBase64 = (bytes: Uint8Array): string => {
  let output = ''
  for (let index = 0; index < bytes.length; index += 3) {
    const first = bytes[index] ?? 0
    const second = bytes[index + 1] ?? 0
    const third = bytes[index + 2] ?? 0
    const packed = (first << 16) | (second << 8) | third

    output += base64Alphabet[(packed >> 18) & 63]
    output += base64Alphabet[(packed >> 12) & 63]
    output += index + 1 < bytes.length ? base64Alphabet[(packed >> 6) & 63] : '='
    output += index + 2 < bytes.length ? base64Alphabet[packed & 63] : '='
  }

  return output
}

const normalizeBase64Secret = (value: string, fieldName: string): string => {
  const normalized = value.replace(/\s/g, '')
  if (normalized.length === 0 || !/^[A-Za-z0-9+/]*={0,2}$/.test(normalized) || normalized.length % 4 !== 0) {
    throw new Error(`${fieldName} must be base64 encoded.`)
  }

  return normalized
}

const decodeBase64SecretChunk = (chunk: string): number[] => {
  const values = [...chunk].map(character => character === '=' ? 0 : base64Alphabet.indexOf(character))
  const packed = ((values[0] ?? 0) << 18) | ((values[1] ?? 0) << 12) | ((values[2] ?? 0) << 6) | (values[3] ?? 0)
  return [
    (packed >> 16) & 255,
    ...(chunk[2] !== '=' ? [(packed >> 8) & 255] : []),
    ...(chunk[3] !== '=' ? [packed & 255] : [])
  ]
}

const base64ToBytes = (value: string, fieldName: string): Uint8Array<ArrayBuffer> => {
  const normalized = normalizeBase64Secret(value, fieldName)
  const bytes: number[] = []
  for (let index = 0; index < normalized.length; index += 4) {
    bytes.push(...decodeBase64SecretChunk(normalized.slice(index, index + 4)))
  }

  const output = new Uint8Array(new ArrayBuffer(bytes.length))
  output.set(bytes)
  return output
}

const toArrayBuffer = (bytes: Uint8Array): ArrayBuffer =>
  bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer

const importExtensionSecretRootKey = async (rootKey: string): Promise<CryptoKey> => {
  const keyBytes = base64ToBytes(rootKey, 'Extension secret root key')
  if (keyBytes.byteLength !== 32) {
    throw new Error('Extension secret root key must decode to 32 bytes.')
  }

  return await crypto.subtle.importKey(
    'raw',
    toArrayBuffer(keyBytes),
    { name: 'AES-GCM' },
    false,
    ['encrypt', 'decrypt']
  )
}

const extensionSecretAdditionalData = (options: ExtensionSecretOptions): Uint8Array =>
  new TextEncoder().encode([
    options.extensionKey,
    options.ownerType,
    options.ownerId,
    options.secretKey,
    String(EXTENSION_SECRET_KEY_VERSION)
  ].join('\u001f'))

/**
 * Encrypts JSON with AES-GCM, binding the ciphertext to its extension owner identity and secret-key name.
 */
const encryptExtensionSecretValue = async (
  options: SetExtensionSecretOptions
): Promise<{ ciphertext: string; iv: string; authTag: string }> => {
  const key = await importExtensionSecretRootKey(options.rootKey)
  const iv = crypto.getRandomValues(new Uint8Array(new ArrayBuffer(EXTENSION_SECRET_IV_BYTES)))
  const encoded = new TextEncoder().encode(JSON.stringify(options.value))
  const encrypted = new Uint8Array(await crypto.subtle.encrypt(
    {
      name: 'AES-GCM',
      iv: toArrayBuffer(iv),
      additionalData: toArrayBuffer(extensionSecretAdditionalData(options)),
      tagLength: EXTENSION_SECRET_TAG_BYTES * 8
    },
    key,
    toArrayBuffer(encoded)
  ))
  const ciphertext = encrypted.slice(0, encrypted.length - EXTENSION_SECRET_TAG_BYTES)
  const authTag = encrypted.slice(encrypted.length - EXTENSION_SECRET_TAG_BYTES)

  return {
    ciphertext: bytesToBase64(ciphertext),
    iv: bytesToBase64(iv),
    authTag: bytesToBase64(authTag)
  }
}

/**
 * Authenticates and decrypts an AES-GCM secret using the same extension owner identity binding.
 */
const decryptExtensionSecretValue = async (
  options: ExtensionSecretOptions & {
    ciphertext: string
    iv: string
    authTag: string
  }
): Promise<JsonValue> => {
  const key = await importExtensionSecretRootKey(options.rootKey)
  const ciphertext = base64ToBytes(options.ciphertext, 'Extension secret ciphertext')
  const authTag = base64ToBytes(options.authTag, 'Extension secret authentication tag')
  const encrypted = new Uint8Array(new ArrayBuffer(ciphertext.length + authTag.length))
  encrypted.set(ciphertext)
  encrypted.set(authTag, ciphertext.length)
  const decrypted = await crypto.subtle.decrypt(
    {
      name: 'AES-GCM',
      iv: toArrayBuffer(base64ToBytes(options.iv, 'Extension secret initialization vector')),
      additionalData: toArrayBuffer(extensionSecretAdditionalData(options)),
      tagLength: EXTENSION_SECRET_TAG_BYTES * 8
    },
    key,
    toArrayBuffer(encrypted)
  )

  return JSON.parse(new TextDecoder().decode(decrypted)) as JsonValue
}

export interface ExtensionStreamContextDatabase {
  Agency_Profile: {
    id: unknown
    _deleted: boolean
  }
  Transfer_Payment_Profile: {
    id: unknown
    egcs_tp_agency: unknown
    _deleted: boolean
  }
  Transfer_Payment_Stream: {
    id: unknown
    egcs_tp_transferpaymentprofile: unknown
    _deleted: boolean
  }
}

export interface ExtensionStreamContextQueryBuilder {
  innerJoin(
    table: 'Transfer_Payment_Profile',
    leftColumn: 'Transfer_Payment_Profile.id',
    rightColumn: 'Transfer_Payment_Stream.egcs_tp_transferpaymentprofile'
  ): ExtensionStreamContextQueryBuilder
  innerJoin(
    table: 'Agency_Profile',
    leftColumn: 'Agency_Profile.id',
    rightColumn: 'Transfer_Payment_Profile.egcs_tp_agency'
  ): ExtensionStreamContextQueryBuilder
  select(columns: [
    'Transfer_Payment_Profile.id as profile_id',
    'Transfer_Payment_Profile.egcs_tp_agency as agency_id'
  ]): ExtensionStreamContextQueryBuilder
  where(
    column:
      | 'Transfer_Payment_Stream.id'
      | 'Transfer_Payment_Stream._deleted'
      | 'Transfer_Payment_Profile._deleted'
      | 'Agency_Profile._deleted',
    operator: '=',
    value: string | boolean
  ): ExtensionStreamContextQueryBuilder
  executeTakeFirst(): Promise<{
    profile_id: unknown
    agency_id: unknown
  } | undefined>
}

export interface ExtensionStreamContextDatabaseClient {
  selectFrom(table: 'Transfer_Payment_Stream'): ExtensionStreamContextQueryBuilder
}

export type ReviewSchemaContentSource = {
  definition?: JsonValue | null
  egcs_cn_scoringmatrix?: JsonValue | null
  egcs_cn_assessmentschema?: JsonValue | null
}

export type ReviewSchemaContent = {
  scoringMatrix: JsonValue | null
  assessmentSchema: JsonValue | null
}

export const EnFrLabelSchema = z.object({
  en: z.string(),
  fr: z.string()
})

const DependencyValueSchema = z.boolean().or(z.coerce.number().or(z.string()))

const HelpersDependencySchema = z.object({
  type: z.literal('helpers'),
  field: z.string()
})

const AnswerDependencySchema = z.object({
  type: z.literal('answers'),
  section: z.string(),
  subsection: z.string(),
  question: z.string()
})

const DependencyOnSchema = z.discriminatedUnion('type', [HelpersDependencySchema, AnswerDependencySchema])

const DependencySchemaBase = z.object({
  on: DependencyOnSchema,
  value: DependencyValueSchema
})

const DependencySchema = DependencySchemaBase.or(z.array(DependencySchemaBase))

const AdjustableWeightSchema = z.object({
  adjustable: z.literal(true),
  on: DependencyOnSchema,
  weights: z.record(z.string(), z.coerce.number())
})

const FixedWeightSchema = z.object({
  adjustable: z.literal(false),
  weight: z.coerce.number()
})

const AdjustableWeightArraySchema = z.tuple([z.coerce.number(), z.array(AdjustableWeightSchema)])

const WeightSchema = AdjustableWeightSchema.or(FixedWeightSchema)

const HelpSchema = z.object({
  title: EnFrLabelSchema,
  description: EnFrLabelSchema
})

const QuestionSchema = z.object({
  type: z.literal('question'),
  name: z.string(),
  question: EnFrLabelSchema,
  weight: WeightSchema,
  commentThreshold: z.object({
    min: z.coerce.number(),
    max: z.coerce.number()
  }),
  options: z.array(z.object({
    value: z.coerce.number(),
    label: EnFrLabelSchema,
    description: EnFrLabelSchema
  })),
  help: z.array(HelpSchema),
  depends: z.optional(z.array(DependencySchema)),
  assistance: z.optional(z.literal('fundingHistory'))
})

const CalculationSchema = z.object({
  type: z.literal('calculation'),
  name: z.string(),
  question: EnFrLabelSchema,
  weight: WeightSchema,
  help: z.array(HelpSchema),
  depends: z.optional(z.array(DependencySchema)),
  formula: z.unknown()
})

const AssessmentQuestionItemSchema = z.discriminatedUnion('type', [QuestionSchema, CalculationSchema])

const ScoringMatrixItemSchema = z.object({
  max: z.coerce.number(),
  label: EnFrLabelSchema,
  indicator: z.string()
})

const OutcomeOptionSchema = z.object({
  max: z.coerce.number(),
  value: z.string(),
  label: EnFrLabelSchema
})

export const AssessmentDefinitionSchema = z.object({
  helpers: z.optional(z.record(z.string(), DependencyValueSchema)),
  sections: z.array(z.object({
    weight: z.coerce.number(),
    number: z.string(),
    label: EnFrLabelSchema,
    name: z.string(),
    icon: z.string(),
    subSections: z.array(z.object({
      name: z.string(),
      weight: WeightSchema.or(AdjustableWeightArraySchema),
      label: EnFrLabelSchema,
      questions: z.array(AssessmentQuestionItemSchema),
      depends: z.optional(z.array(DependencySchema))
    }))
  })),
  sectionMatrix: z.array(ScoringMatrixItemSchema),
  outcomes: z.array(z.object({
    label: EnFrLabelSchema,
    name: z.string(),
    strategies: z.array(z.object({
      name: z.string(),
      label: EnFrLabelSchema,
      options: z.array(OutcomeOptionSchema)
    }))
  })),
  impactors: z.optional(z.array(z.object({
    weight: z.coerce.number(),
    on: DependencyOnSchema,
    scoringMatrix: z.array(z.object({
      max: z.coerce.number(),
      value: z.coerce.number()
    })),
    label: z.optional(EnFrLabelSchema)
  })))
})

export type AssessmentDefinition = z.infer<typeof AssessmentDefinitionSchema>

/**
 * Resolves review-schema content from an exact canonical publication definition.
 */
export const getReviewSchemaEffectiveContent = (schema: ReviewSchemaContentSource): ReviewSchemaContent => {
  const definition = schema.definition && typeof schema.definition === 'object' && !Array.isArray(schema.definition)
    ? schema.definition as Record<string, JsonValue>
    : null
  return {
    scoringMatrix: definition?.scoringMatrix ?? schema.egcs_cn_scoringmatrix ?? null,
    assessmentSchema: definition?.assessmentSchema ?? schema.egcs_cn_assessmentschema ?? null
  }
}

/**
 * Resolves the host stream, transfer payment profile, agency, and extension scope for an extension route.
 *
 * @param db Minimal Kysely-compatible host database client.
 * @param streamId Transfer payment stream id from the extension route.
 * @returns The resolved extension stream context, or null when the stream is unavailable.
 */
export const resolveExtensionStreamContext = async (
  db: ExtensionStreamContextDatabaseClient,
  streamId: string
): Promise<ExtensionStreamContext | null> => {
  const stream = await db
    .selectFrom('Transfer_Payment_Stream')
    .innerJoin('Transfer_Payment_Profile', 'Transfer_Payment_Profile.id', 'Transfer_Payment_Stream.egcs_tp_transferpaymentprofile')
    .innerJoin('Agency_Profile', 'Agency_Profile.id', 'Transfer_Payment_Profile.egcs_tp_agency')
    .select([
      'Transfer_Payment_Profile.id as profile_id',
      'Transfer_Payment_Profile.egcs_tp_agency as agency_id'
    ])
    .where('Transfer_Payment_Stream.id', '=', streamId)
    .where('Transfer_Payment_Stream._deleted', '=', false)
    .where('Transfer_Payment_Profile._deleted', '=', false)
    .where('Agency_Profile._deleted', '=', false)
    .executeTakeFirst()

  if (!stream) return null

  const agencyId = String(stream.agency_id)
  const profileId = String(stream.profile_id)
  return {
    agencyId,
    profileId,
    streamId,
    scope: {
      type: 'entity',
      agencyId,
      path: [
        { type: 'transfer_payment', id: profileId },
        { type: 'transfer_payment_stream', id: streamId }
      ]
    }
  }
}

/**
 * Creates or updates a host-managed extension key-value entry.
 *
 * @param db Minimal Kysely-compatible host database client.
 * @param extensionKey Extension manifest key.
 * @param ownerType Host entity owner type.
 * @param ownerId Host entity owner id.
 * @param configKey Extension-owned value key.
 * @param value JSON value to store.
 * @returns Inserted or updated row when the host adapter returns it.
 */
export const setExtensionKvEntry = async (
  db: Kysely<ExtensionKvDatabase>,
  extensionKey: string,
  ownerType: string,
  ownerId: string,
  configKey: string,
  value: JsonValue
) => {
  const existing = await db
    .selectFrom('extensions.kv_entry')
    .select('id')
    .where('extension_key', '=', extensionKey)
    .where('owner_type', '=', ownerType)
    .where('owner_id', '=', ownerId)
    .where('config_key', '=', configKey)
    .where('_deleted', '=', false)
    .executeTakeFirst()

  if (existing) {
    return await db
      .updateTable('extensions.kv_entry')
      .set({ value })
      .where('id', '=', existing.id)
      .returningAll()
      .executeTakeFirst()
  }

  return await db
    .insertInto('extensions.kv_entry')
    .values({
      extension_key: extensionKey,
      owner_type: ownerType,
      owner_id: ownerId,
      config_key: configKey,
      value,
      _deleted: false
    })
    .returningAll()
    .executeTakeFirst()
}

/**
 * Reads a host-managed extension key-value entry.
 *
 * @param db Minimal Kysely-compatible host database client.
 * @param extensionKey Extension manifest key.
 * @param ownerType Host entity owner type.
 * @param ownerId Host entity owner id.
 * @param configKey Extension-owned value key.
 * @returns Stored JSON value, or null when absent.
 */
export const getExtensionKvEntry = async (
  db: Kysely<ExtensionKvDatabase>,
  extensionKey: string,
  ownerType: string,
  ownerId: string,
  configKey: string
): Promise<JsonValue | null> => {
  const row = await db
    .selectFrom('extensions.kv_entry')
    .select('value')
    .where('extension_key', '=', extensionKey)
    .where('owner_type', '=', ownerType)
    .where('owner_id', '=', ownerId)
    .where('config_key', '=', configKey)
    .where('_deleted', '=', false)
    .executeTakeFirst()

  return row ? row.value : null
}

/**
 * Soft-deletes a host-managed extension key-value entry.
 *
 * @param db Minimal Kysely-compatible host database client.
 * @param extensionKey Extension manifest key.
 * @param ownerType Host entity owner type.
 * @param ownerId Host entity owner id.
 * @param configKey Extension-owned value key.
 */
export const deleteExtensionKvEntry = async (
  db: Kysely<ExtensionKvDatabase>,
  extensionKey: string,
  ownerType: string,
  ownerId: string,
  configKey: string
) => {
  await db
    .updateTable('extensions.kv_entry')
    .set({ _deleted: true })
    .where('extension_key', '=', extensionKey)
    .where('owner_type', '=', ownerType)
    .where('owner_id', '=', ownerId)
    .where('config_key', '=', configKey)
    .where('_deleted', '=', false)
    .execute()
}

/**
 * Creates or updates an encrypted host-managed extension secret.
 *
 * @param db Minimal Kysely-compatible host database client.
 * @param options Secret owner, key, root encryption key, value, and optional metadata.
 * @returns Inserted or updated row when the host adapter returns it.
 */
export const setEncryptedExtensionSecret = async <Database extends ExtensionSecretDatabase>(
  db: ExtensionSecretDatabaseClient<Database>,
  options: SetExtensionSecretOptions
) => {
  const secretDb = asExtensionSecretDatabase(db)
  const encrypted = await encryptExtensionSecretValue(options)
  const existing = await secretDb
    .selectFrom('extensions.secret_entry')
    .select('id')
    .where('extension_key', '=', options.extensionKey)
    .where('owner_type', '=', options.ownerType)
    .where('owner_id', '=', options.ownerId)
    .where('secret_key', '=', options.secretKey)
    .where('_deleted', '=', false)
    .executeTakeFirst()

  const values = {
    ciphertext: encrypted.ciphertext,
    iv: encrypted.iv,
    auth_tag: encrypted.authTag,
    algorithm: EXTENSION_SECRET_ALGORITHM,
    key_version: EXTENSION_SECRET_KEY_VERSION,
    metadata: options.metadata ?? {},
    updated_at: new Date()
  }

  if (existing) {
    return await secretDb
      .updateTable('extensions.secret_entry')
      .set(values)
      .where('id', '=', existing.id)
      .returningAll()
      .executeTakeFirst()
  }

  return await secretDb
    .insertInto('extensions.secret_entry')
    .values({
      extension_key: options.extensionKey,
      owner_type: options.ownerType,
      owner_id: options.ownerId,
      secret_key: options.secretKey,
      ...values,
      _deleted: false
    })
    .returningAll()
    .executeTakeFirst()
}

/**
 * Reads and decrypts a host-managed extension secret.
 *
 * @param db Minimal Kysely-compatible host database client.
 * @param options Secret owner, key, and root encryption key.
 * @returns Decrypted JSON value, or null when absent.
 */
export const getEncryptedExtensionSecret = async <Database extends ExtensionSecretDatabase>(
  db: ExtensionSecretDatabaseClient<Database>,
  options: ExtensionSecretOptions
): Promise<JsonValue | null> => {
  const secretDb = asExtensionSecretDatabase(db)
  const row = await secretDb
    .selectFrom('extensions.secret_entry')
    .select(['ciphertext', 'iv', 'auth_tag', 'algorithm', 'key_version'])
    .where('extension_key', '=', options.extensionKey)
    .where('owner_type', '=', options.ownerType)
    .where('owner_id', '=', options.ownerId)
    .where('secret_key', '=', options.secretKey)
    .where('_deleted', '=', false)
    .executeTakeFirst()

  if (!row) {
    return null
  }

  if (row.algorithm !== EXTENSION_SECRET_ALGORITHM || row.key_version !== EXTENSION_SECRET_KEY_VERSION) {
    throw new Error('Unsupported extension secret encryption metadata.')
  }

  return await decryptExtensionSecretValue({
    ...options,
    ciphertext: row.ciphertext,
    iv: row.iv,
    authTag: row.auth_tag
  })
}

/**
 * Soft-deletes a host-managed extension secret.
 *
 * @param db Minimal Kysely-compatible host database client.
 * @param extensionKey Extension manifest key.
 * @param ownerType Host or extension owner type.
 * @param ownerId Host or extension owner id.
 * @param secretKey Extension-owned secret key.
 */
export const deleteEncryptedExtensionSecret = async <Database extends ExtensionSecretDatabase>(
  db: ExtensionSecretDatabaseClient<Database>,
  extensionKey: string,
  ownerType: string,
  ownerId: string,
  secretKey: string
) => {
  const secretDb = asExtensionSecretDatabase(db)
  await secretDb
    .updateTable('extensions.secret_entry')
    .set({ _deleted: true, updated_at: new Date() })
    .where('extension_key', '=', extensionKey)
    .where('owner_type', '=', ownerType)
    .where('owner_id', '=', ownerId)
    .where('secret_key', '=', secretKey)
    .where('_deleted', '=', false)
    .execute()
}
